apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: probe
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - image: ghcr.io/probeit/probe:v0.1.4
          name: probe
          ports:
            - containerPort: 8943
